// import clock from "../images/portfolio/clock.png";
const FiltaringPortfolio = [
  {
    id: 1,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "react",
  },
  {
    id: 2,
    img: "https://i.ibb.co/rmKw4cs/Screenshot-1.png",
    projectName: "Traveling website",
    description: "this is full stack website",
    liveLink: "https://travelin-assignment-11.web.app/",
    clintLink:
      "https://github.com/rjamil336/travelin-website-react-js-client-side",
    serverLink: "https://github.com/rjamil336/traveling-server",
    category: "react",
  },
  {
    id: 3,
    img: "https://i.ibb.co/h2YCTdJ/Screenshot-2.png",
    projectName: "Health care",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/health-care-website",
    category: "react",
  },
  {
    id: 4,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "javascript",
  },
  {
    id: 5,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "javascript",
  },
  {
    id: 6,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "javascript",
  },
  {
    id: 7,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "javascript",
  },
  {
    id: 8,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "bootstrap",
  },
  {
    id: 9,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "bootstrap",
  },
  {
    id: 10,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "bootstrap",
  },
  {
    id: 11,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "css",
  },
  {
    id: 12,
    img: "https://i.ibb.co/C85qYwP/clock.png",
    projectName: "clock web site",
    description: "this is full stack website",
    liveLink: "https://jamilrayhan-clock-website.web.app/",
    clintLink: "https://github.com/rjamil336/MERN_STACK_PROJECT",
    serverLink: "https://github.com/rjamil336/CLOCK_WEBSITE_SERVER_SITE",
    category: "css",
  },
];

export default FiltaringPortfolio;
